# Generated by Django 5.2.17 on 2026-10-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_businessinvitation_role_and_more'),
        ('integrations', '0006_encrypt_plaintext_config_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='financial_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_source_businesses', to='integrations.businessconnector'),
        ),
        migrations.AddField(
            model_name='business',
            name='financial_source_mode',
            field=models.CharField(choices=[('external', 'External accounting'), ('manual', 'Manual journal')], default='external', max_length=16),
        ),
    ]
