# Generated by Django 5.2.17 on 2026-09-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_conversation_task_tasks_task_convers_176087_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'reminder_at'), name='unique_task_reminder_delivery')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reminder_at'], name='tasks_due_reminder_idx'),
        ),
    ]
