# Generated by Django 5.2.17 on 2026-09-30 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useravatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('auth_epoch', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_change', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
