# Generated by Django 5.2.17 on 2026-10-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0005_aitoolcalllog_attempts_aitoolcalllog_executed_at_and_more'),
        ('bots', '0010_botmessage_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessknowledgeitem',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_items', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='businessknowledgeitem',
            name='connected_agents',
            field=models.ManyToManyField(blank=True, related_name='connected_knowledge_items', to='bots.bot'),
        ),
    ]
