# Generated by Django 5.2.17 on 2026-10-06 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0006_agent_knowledge_isolation'),
        ('bots', '0010_botmessage_delivery_attempts_and_more'),
        ('businesses', '0011_financial_analysis_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('staff', 'Employee'), ('inbox', 'Customer')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_archived', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('memory_epoch', models.PositiveIntegerField(default=0)),
                ('memory_since', models.DateTimeField(blank=True, null=True)),
                ('memory_json', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_conversations', to='bots.bot')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to='businesses.business')),
                ('inbox_conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory', to='bots.botconversation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('clarifying', 'Needs information'), ('awaiting_confirmation', 'Needs confirmation'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('superseded', 'Replaced')], default='preparing', max_length=32)),
                ('mode', models.CharField(default='work', max_length=16)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('sources_json', models.JSONField(blank=True, default=list)),
                ('references_json', models.JSONField(blank=True, default=list)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('access_fingerprint', models.CharField(max_length=64)),
                ('runtime_fingerprint', models.CharField(max_length=64)),
                ('memory_epoch', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ai_core.agentconversation')),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_turns', to='ai_core.airequestlog')),
                ('tool_calls', models.ManyToManyField(blank=True, related_name='agent_turns', to='ai_core.aitoolcalllog')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['business', 'agent', 'owner', 'is_archived', 'updated_at'], name='ai_thread_owner_recent'),
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inbox_conversation__isnull', True), ('kind', 'staff')), models.Q(('inbox_conversation__isnull', False), ('kind', 'inbox'), ('owner__isnull', True)), _connector='OR'), name='ai_thread_scope_kind'),
        ),
        migrations.AddIndex(
            model_name='agentturn',
            index=models.Index(fields=['conversation', 'status', 'created_at'], name='ai_turn_thread_status'),
        ),
        migrations.AddConstraint(
            model_name='agentturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='ai_turn_sequence'),
        ),
        migrations.AddConstraint(
            model_name='agentturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'idempotency_key'), name='ai_turn_request_key'),
        ),
        migrations.AddConstraint(
            model_name='agentturn',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['preparing', 'executing'])), fields=('conversation',), name='ai_turn_one_running'),
        ),
    ]
