# Generated by Django 5.2.17 on 2026-09-28 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_businessinvitation_role_and_more'),
        ('core', '0010_crmcommandidempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='scan_attempts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_engine',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_error_code',
            field=models.CharField(blank=True, editable=False, max_length=48),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_next_attempt_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Blocked'), ('error', 'Scan unavailable')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scan_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='scanned_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['scan_status', 'scan_next_attempt_at'], name='attachment_scan_due_idx'),
        ),
    ]
