Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.sock
LocalSocketMode 660
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 2
MaxQueue 20
StreamMaxLength 10M
MaxFileSize 10M
MaxScanSize 40M
MaxScanTime 20000
MaxRecursion 16
MaxFiles 1000
AlertExceedsMax yes
AlertEncrypted yes
ReadTimeout 30
CommandReadTimeout 5
SelfCheck 60
