import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { crmSession } from "./support/crm-workspace";
import type { Bot, Client } from "../src/types";

test("agent CRM lookup and period analytics use actual scoped records and recover from report failure", async ({ page }, info) => {
  test.skip(process.env.ZANI_QUALITY_GATE !== "1", "Disposable fixture database required");
  test.setTimeout(180_000);
  page.setDefaultTimeout(15_000);
  const session = await crmSession(page);
  const bot = await session.create<Bot>("bots", { name: "Analytical controls", scenario: "crm" });
  await session.action(`bots/${bot.id}/activate`);
  const api = process.env.E2E_API_BASE_URL || "http://127.0.0.1:8000";
  const configured = await page.request.patch(`${api}/api/businesses/${session.business}/`, { headers: session.headers, data: { financial_source_mode: "manual", financial_connector: null } });
  expect(configured.ok()).toBeTruthy();
  const client = await session.create<Client>("clients", { full_name: "Synthetic analytical client" });
  const baseline = await session.read("ai/analyst/history", { business: session.business, agent: bot.id, start: "2025-04-01", end: "2025-04-30" });
  await session.create("client-payments", { client: client.id, amount: "100.25", currency: "KZT", occurred_at: "2025-04-15T10:00:00Z", method: "cash", submission_id: randomUUID() });
  await page.goto(`/app/ai-agents/${bot.id}/work`);
  const editor = page.getByTestId("ai-agent-editor");
  await editor.locator("summary").filter({ hasText: "Действия с CRM" }).click();
  const commands = editor.getByRole("region", { name: "Действия с CRM", exact: true });
  await commands.getByLabel("Раздел CRM", { exact: true }).click();
  await page.getByRole("option", { name: "Клиенты", exact: true }).click();
  await commands.getByLabel("Поиск", { exact: true }).fill(client.full_name);
  await commands.getByLabel("Запись для действия", { exact: true }).click();
  await page.getByRole("option", { name: `${client.full_name} · #${client.id}`, exact: true }).click();
  const link = commands.getByRole("link", { name: client.full_name, exact: true });
  await expect(link).toHaveAttribute("href", `/app/clients?client=${client.id}`);
  await commands.getByRole("checkbox").check();
  await expect(commands.getByRole("button", { name: "Назад", exact: true })).toBeDisabled();
  await editor.getByRole("tab", { name: "Аналитика", exact: true }).click();
  await editor.getByLabel("Начало периода", { exact: true }).fill("2025-04-01");
  await editor.getByLabel("Конец периода", { exact: true }).fill("2025-04-30");
  const reportResponse = page.waitForResponse(response => response.request().method() === "GET" && response.url().includes("/api/ai/analyst/history/") && response.url().includes("2025-04-01"));
  await editor.getByRole("button", { name: "Показать", exact: true }).click();
  const report = await (await reportResponse).json();
  expect(Number(report.financial.net_receipts)).toBe(Number(baseline.financial.net_receipts) + 100.25);
  await editor.getByText("Динамика поступлений и возвратов", { exact: true }).click();
  await expect(editor.getByRole("rowheader", { name: "2025-04-15", exact: true })).toBeVisible();
  await editor.getByLabel("Начало периода вопроса", { exact: true }).fill("2025-04-01");
  await editor.getByLabel("Конец периода вопроса", { exact: true }).fill("2025-04-30");
  await editor.getByLabel("Вопрос по выбранному периоду", { exact: true }).fill("Explain the recorded receipts for this period.");
  const answerResponse = page.waitForResponse(response => response.request().method() === "POST" && /\/api\/ai\/conversations\/[^/]+\/turns\/$/.test(response.url()));
  await editor.getByRole("button", { name: "Отправить", exact: true }).click();
  const answer = await answerResponse;
  expect(answer.status()).toBe(200);
  expect(answer.request().postDataJSON()).toMatchObject({ mode: "analytics", period: { start: "2025-04-01", end: "2025-04-30" } });
  await expect(editor.getByText((await answer.json()).response, { exact: true })).toBeVisible();
  await editor.getByLabel("Начало периода вопроса", { exact: true }).fill("2025-05-01");
  await editor.getByLabel("Вопрос по выбранному периоду", { exact: true }).fill("Next question");
  await expect(editor.getByRole("button", { name: "Отправить", exact: true })).toBeDisabled();
  await page.route("**/api/ai/analyst/history/?**", route => route.fulfill({ status: 503, json: { detail: "Synthetic report failure" } }));
  await editor.getByLabel("Начало периода", { exact: true }).fill("2025-05-01");
  await editor.getByLabel("Конец периода", { exact: true }).fill("2025-05-31");
  await editor.getByRole("button", { name: "Показать", exact: true }).click();
  await expect(editor.getByRole("alert")).toBeVisible();
  await page.unroute("**/api/ai/analyst/history/?**");
  await editor.getByRole("button", { name: "Повторить", exact: true }).click();
  await expect(editor.getByRole("alert")).toHaveCount(0);
  const briefResponse = page.waitForResponse(response => response.request().method() === "GET" && response.url().includes("/analyst/brief/"));
  await editor.getByRole("button", { name: "Подготовить сводку по событиям", exact: true }).click();
  expect((await briefResponse).status()).toBe(200);
  await page.screenshot({ path: info.outputPath("analytical-controls.png"), fullPage: true });
});
