import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { crmSession } from "./support/crm-workspace";
import type { AgentProfile, Bot } from "../src/types";

test.beforeEach(({ page }) => {
  page.setDefaultTimeout(15_000);
  test.skip(process.env.ZANI_QUALITY_GATE !== "1", "Requires isolated fixtures and mock AI");
  test.setTimeout(240_000);
});

test("creation requires purpose; CRM settings drive work, approval and analytics", async ({ page }, info) => {
  const session = await crmSession(page);
  await page.goto("/app/ai-agents");
  await page.getByTestId("agent-navigation").getByRole("button", { name: "Создать агента", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Новый агент" });
  await dialog.getByRole("textbox").fill("CRM workspace");
  const create = dialog.getByRole("button", { name: "Создать агента", exact: true });
  await expect(create).toBeDisabled();
  const inbox = dialog.getByRole("radio", { name: /^Общение с клиентами/ });
  await dialog.getByText("CRM и аналитика", { exact: true }).hover();
  await expect(page.getByRole("tooltip")).toHaveCount(0);
  await inbox.focus();
  await inbox.press("Space");
  await inbox.press("ArrowDown");
  await expect(dialog.getByRole("radio", { name: /^CRM и аналитика/ })).toBeChecked();
  await dialog.getByRole("button", { name: "Подробнее: CRM и аналитика", exact: true }).focus();
  await expect(page.getByRole("tooltip")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(dialog).toBeVisible();
  await page.screenshot({ path: info.outputPath("create-crm.png"), fullPage: true });
  const posted = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/api/bots/"));
  await create.click();
  const response = await posted;
  expect(response.status()).toBe(201);
  const bot: Bot = await response.json();
  expect(bot.scenario).toBe("crm");
  await expect(page).toHaveURL(new RegExp(`/ai-agents/${bot.id}/profile$`));
  const editor = page.getByTestId("ai-agent-editor");
  await expect(editor.getByRole("tab")).toHaveCount(5);
  await expect(editor.getByRole("tab", { name: "Каналы", exact: true })).toHaveCount(0);
  await expect(editor.getByRole("button", { name: "Шаблон: администратор стоматологии" })).toHaveCount(0);
  await editor.getByRole("textbox", { name: "Главная инструкция", exact: true }).fill("Use only enabled sources and show the evidence.");
  await editor.getByRole("button", { name: "Сохранить изменения", exact: true }).click();
  await expect(editor.getByRole("button", { name: "Сохранить изменения", exact: true })).toBeDisabled();
  await editor.getByRole("tab", { name: "Знания", exact: true }).click();
  for (const name of ["Клиенты", "Заявки", "Сделки", "Календарь"]) await editor.getByRole("checkbox", { name, exact: true }).uncheck();
  await editor.getByRole("button", { name: "Сохранить изменения", exact: true }).click();
  await expect(editor.getByRole("button", { name: "Сохранить изменения", exact: true })).toBeDisabled();
  await editor.getByRole("tab", { name: "Действия", exact: true }).click();
  await editor.getByRole("checkbox", { name: "Создать запись CRM", exact: true }).check();
  await editor.getByRole("button", { name: "Сохранить изменения", exact: true }).click();
  await expect(editor.getByRole("button", { name: "Сохранить изменения", exact: true })).toBeDisabled();
  const saved = (await session.list<AgentProfile>("ai/agent-profiles")).find(profile => profile.bot === bot.id)!;
  expect(saved.rules_json.sources).toEqual(["knowledge", "tasks"]);
  expect(saved.allowed_tools_json.tools).toEqual(["crm_read", "crm_create"]);
  expect(saved.system_prompt).toBe("Use only enabled sources and show the evidence.");
  await editor.getByRole("switch", { name: "Изменить статус агента CRM workspace" }).click();
  await expect.poll(async () => (await session.read(`bots/${bot.id}`)).status).toBe("active");
  await editor.getByRole("tab", { name: "Работа с CRM", exact: true }).click();
  await expect(editor.getByLabel("Раздел CRM", { exact: true })).toContainText("Задачи");
  await editor.getByRole("textbox", { name: "Вопрос AI", exact: true }).fill("What tasks need attention?");
  const chat = page.waitForRequest(request => request.url().endsWith("/api/ai/assistant/chat/") && request.method() === "POST");
  await editor.getByRole("button", { name: "Спросить AI", exact: true }).click();
  expect((await chat).postDataJSON().agent).toBe(bot.id);
  await expect(editor.getByRole("button", { name: "Спросить AI", exact: true })).toBeEnabled();
  const title = `Confirmed ${info.project.name}`;
  const proposal = await session.action("ai/tools/suggest", { business: session.business, agent: bot.id, tool_name: "crm_create", arguments: { entity: "tasks", values: { title } } });
  expect(proposal.suggested_actions[0].input_json._agent.agent_id).toBe(bot.id);
  await page.route("**/api/ai/crm/plan/", async route => {
    expect(route.request().postDataJSON().agent).toBe(bot.id);
    await route.fulfill({ json: { question: "", suggested_actions: proposal.suggested_actions } });
  });
  await editor.getByRole("textbox", { name: "Что нужно сделать?", exact: true }).fill(`Create task ${title}`);
  await editor.getByRole("button", { name: "Подготовить действие", exact: true }).click();
  const review = editor.getByRole("region", { name: "Проверка действия", exact: true });
  await review.getByRole("button", { name: "Подтвердить", exact: true }).click();
  const confirm = page.getByRole("dialog", { name: "Выполнить проверенное действие?" });
  await confirm.getByRole("button", { name: "Отмена", exact: true }).click();
  expect((await session.list<{ title: string }>("tasks")).some(task => task.title === title)).toBeFalsy();
  await review.getByRole("button", { name: "Подтвердить", exact: true }).click();
  await confirm.getByRole("button", { name: "Подтвердить", exact: true }).click();
  await expect(editor.getByText("Действие выполнено", { exact: true })).toBeVisible();
  expect((await session.list<{ title: string }>("tasks")).filter(task => task.title === title)).toHaveLength(1);
  await page.screenshot({ path: info.outputPath("crm-work-confirmed.png"), fullPage: true });
  await editor.getByRole("tab", { name: "Аналитика", exact: true }).click();
  await expect(editor.getByRole("heading", { name: "История и финансовый анализ", exact: true })).toBeVisible();
  await expect.poll(async () => editor.locator('[role="alert"]').count()).toBe(0);
  for (const locale of ["ru", "kk", "en"]) {
    await page.evaluate(value => localStorage.setItem("ai_smb_language", value), locale);
    await page.reload();
    await expect(editor.getByRole("tab")).toHaveCount(5);
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    const violations = (await new AxeBuilder({ page }).include('[data-testid="ai-agent-editor"]').withTags(["wcag2a", "wcag2aa"]).analyze()).violations;
    expect(violations).toEqual([]);
    await page.screenshot({ path: info.outputPath(`crm-analytics-${locale}.png`), fullPage: true });
  }
});

test("customer creation keeps its own interface and duplicate CRM choice is disabled", async ({ page }, info) => {
  const session = await crmSession(page);
  if (!(await session.list<Bot>("bots")).some(bot => bot.scenario === "crm")) await session.create("bots", { name: "CRM", scenario: "crm" });
  await page.goto("/app/ai-agents");
  await page.getByTestId("agent-navigation").getByRole("button", { name: "Создать агента", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Новый агент" });
  await expect(dialog.getByRole("radio", { name: /^CRM и аналитика/ })).toBeDisabled();
  await dialog.getByRole("textbox").fill("Customer inbox");
  await dialog.getByRole("radio", { name: /^Общение с клиентами/ }).check();
  const posted = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/api/bots/"));
  await dialog.getByRole("button", { name: "Создать агента", exact: true }).click();
  const bot: Bot = await (await posted).json();
  expect(bot.scenario).toBe("inbox");
  const editor = page.getByTestId("ai-agent-editor");
  await expect(editor.getByRole("tab", { name: "Каналы", exact: true })).toBeVisible();
  await expect(editor.getByRole("tab", { name: "Работа с CRM", exact: true })).toHaveCount(0);
  await expect(editor.getByRole("switch", { name: "Изменить статус агента Customer inbox" })).toBeDisabled();
  await expect(editor.getByRole("button", { name: "Шаблон: администратор стоматологии" })).toBeVisible();
  await page.screenshot({ path: info.outputPath("customer-profile.png"), fullPage: true });
});

test("staff use CRM without configuration access and old routes redirect", async ({ page }, info) => {
  const owner = await crmSession(page);
  let bot = (await owner.list<Bot>("bots")).find(bot => bot.scenario === "crm");
  if (!bot) bot = await owner.create<Bot>("bots", { name: "Staff CRM", scenario: "crm" });
  if (bot.status !== "active") await owner.action(`bots/${bot.id}/activate`);
  await page.context().clearCookies();
  await page.evaluate(() => localStorage.clear());
  const session = await crmSession(page, "business_manager@example.com");
  await page.goto("/app/ai-assistant");
  await expect(page).toHaveURL(new RegExp(`/ai-agents/${bot.id}/work$`));
  await expect(page.getByRole("textbox", { name: "Вопрос AI", exact: true })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Профиль", exact: true })).toHaveCount(0);
  await expect(page.locator('[data-focus-return-id="ai-agent-create"]')).toHaveCount(0);
  const directory = await session.read("ai/agents", { business: session.business });
  expect(directory[0].settings_json).toBeUndefined();
  await page.screenshot({ path: info.outputPath("staff-workspace.png"), fullPage: true });
});
